### PR TITLE
Refactor and Factory Generation

### PR DESCRIPTION
**Pull request by cmoesel**
This PR includes a major refactoring of how code is generated.  Now a `CodeWriter` class is used to easily manage indents, code blocks, and comment blocks.

This also generates a new top-level factory and namespace-level factories.

Lastly it improves the generated jsdoc comments to indicate parameters, return types, etc.  This should make the classes even easier to work with in IDEs.

### CODE REVIEW

**Comment by cmoesel** [comment]
You can download the currently generated files from my transfer:
http://employeeshare.mitre.org/c/cmoesel/transfer/SHR/shr_es6_w_factories.zip

The top-level factory is `ObjectFactor.js` in the root.  The namespace-level factories are in their respective namespace folders, with names like `ShrActorObjectFactory.js`.

**Comment by gregquinn2001** [comment]
Thanks Chris. this looks like some great changes to the exporter. I think I mentioned I was having a javascript issue which turned out to be due to circular references. Basically when a class is deserializing itself from json, it may need to use the factories to instantiate a set of classes off a common base class (like Observation or Condition). That was resulting in circular logic. Julia came up with a solution that we manually modified some of the generated classes to do. We need to discuss it with you and decide how we want to proceed. I'm at the ACTO meetings in Chicago for the rest of this week though so it will have to wait until Monday. Feel free to talk to Julia about it though if you want to learn more before Monday.

**Comment by cmoesel** [comment]
Thanks, Greg.  I'm just seeing this now, and I'll be at AMIA Mon-Wed next week.  That said, I'll see if Julia has time to talk this afternoon.

Seeing as this branch still needs further review / potential modification, I just pushed two more commits that are pretty simple, but I had locally.  New files are here: http://employeeshare.mitre.org/c/cmoesel/transfer/SHR/shr_es6_w_factories_2.zip

**Comment by jafeltra** [comment]
I just talked to Chris about what we changed manually in the generated classes. Here are the resources I used when coming up with the fix we have now:

https://esdiscuss.org/topic/how-to-solve-this-basic-es6-module-circular-dependency-problem
https://stackoverflow.com/questions/38841469/how-to-fix-this-es6-module-circular-dependency (This has the answer that is eventually reached in the first link).

**Comment by cmoesel** [comment]
@gregquinn2001, since the circular dependencies only get introduced with deserialization, can we accept this PR as-is, and then address the circular dependencies when we start generating deserialization code?

While I think the workaround that Flux is using now works OK as a short-term fix, I think we should try some other things when we start generating deserialization.

One other thing for consideration...  I mirrored the current approach in this code, but I'd actually prefer that deserialization happen in static methods (e.g., `fromJSON`, `fromFHIRdstu2`) rather than in constructors.  For constructors I'd rather see something like the constructor allowing you to pass in the _value_ (for elements that have values).  Thoughts?

**Comment by cmoesel** [comment]
Might as well add some tests.  These will be helpful for reproducing circular dependencies in the future.

**Comment by gregquinn2001** [comment]
That's what the constructor does. it receives the json and sets elements based on those. There's no code to actually load the content; that's handled externally.

I'll check out the pull request and approve. We should be able to pull in your auto-generated factories, but we won't be able to pull in any new auto-generated classes for the SHR types until we figure out the deserialization.

**Pull request merged**
