### PR TITLE
fromFHIR support

### PR DESCRIPTION
**Pull request by dehall**
Adds support for instantiating SHR classes based on mapped FHIR resources. Each class gets a new, static `fromFHIR` function which takes in the relevant FHIR resource, along with other relevant data to produce the SHR object from. See prior discussion on #27 

Note that because of issues identified in the toFHIR logic while creating this, this disables the toFHIR function, though it can be re-enabled by setting a flag in `generateClass.js`

### CODE REVIEW

**Comment by cmoesel** [comment]
There are 112 commits here.  @dehall and @okeefm -- do you think there is value in keeping all 112?  Or should we squash them all? or is there a meaningful way we can rebase and group commits together (for fewer total commits)?

**Comment by cmoesel** [comment]
I'm also seeing this error (or variants of it) a lot when I run it against my `` branch of `shr_spec`:
```
ERROR: unable to find field with identifer _Entry on element shr.base.InformationItem
Original Element: shr.base.InformationItem ; full mapping: <_Entry>.<shr.base.EntryId> ; FHIR Path: DomainResource.id ID: DomainResource:shr-base-InformationItem.id
```
The `_Entry` is a special syntax to refer to an entry field from and SHR EntryElement.  If the ES6 exporter is already handling the mapping of entry fields, we may want to just ignore this when we see it (and not throw an error) -- otherwise we probably need to add support for it.  Removing the mapping from the CIMPL definitions is also probably a viable short-term solution, if preferred.

**Comment by cmoesel** [comment]
I'm also remembering that the logger isn't really properly implemented right now (or it's at least not tied into the CLI correctly).  I can probably take a look at that and fix it.

**Comment by cmoesel** [comment]
OK, Bunyan logger is integrated.

**Comment by cmoesel** [comment]
I've just fixed an issue where it wasn't properly handling `<_Entry>` -- and now that it's fixed, `<_Entry>` mappings are ignored, which I think is OK in our case.

**Comment by dehall** [comment]
I'm fine with squashing here, though the commits for any particular feature are likely scattered rather than sequential so there isn't going to be a super clean way to do it. No objections to squashing to 1 commit (which you can now do directly on GitHub, btw) or keeping them separate. If you want to try to condense them into 112 < n < 1 commits that's fine too but I'm not sure it's worth spending a lot of time.

**Pull request merged**
