### PR TITLE
Chained setters to support curation

### PR DESCRIPTION
**Pull request by jgibson**
These are a batch of changes to support the curation study. It should not be merged yet because we'll want the #8 changes as well. Probably with built-in type handling.

### CODE REVIEW

**Comment by gregquinn2001** [comment]
@jgibson could you provide a little more detail on these changes? When you added method chaining for setters, did you maintain backward compatibility with existing setters? So if we use the existing setters and ignore any return argument (since there wasn't one before), will our current code still work? Or maybe even more simply, did you change the names of the existing setters (whether they return an object or not now)?

**Comment by gregquinn2001** [comment]
In the future, if you are planning to push changes for use by curation study and Flux notes, could you add Dan and I as reviewers like you add Chris? That way we know to look at the pull request.

**Comment by cmoesel** [comment]
@jgibson -- I just merged #8, which you indicated you were waiting on.  Should I wait for this PR to be ready before bumping the es6-export version number and releasing?

**Comment by jgibson** [comment]
In preparation for Chris' upcoming `shr-cli` release here is a minor enhancement to add chained setters to the es6 class generator. In addition the modules sanity checking is now supported in by the es6 class generator.

**Pull request merged**
